# FontAwesome icons reference: https://fontawesome.com/v6/search?o=r&m=free
icon: washing-machine
tasks:
  - name: Clean Lint Trap
    icon: wind
  - name: Wipe Machines
    icon: soap
  - name: Sweep Floor
    icon: broom
  - name: Organize Supplies
    icon: box
  - name: Empty Trash
    icon: trash
  - name: Clean Sink
    icon: sink 